### ISSUE TITLE
TypeError at MusicList.get_page_type

### ISSUE THREAD

**Issue by suitougreentea** [kenji0919/pirodx_manager#86]
DebugPageで、test dl_result_by_music_nameを実行した際に発生。再現性不明。

なんでここで躓いたんだろう。要検証です。

```
TypeError: Cannot read property 'indexOf' of undefined
    at Function.MusicList.get_page_type (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:60541:95)
    at chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:47171:23
    at chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:26273:12
    at processQueue (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:30087:28)
    at chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:30103:28
    at Scope.$eval (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:31300:29)
    at Scope.$digest (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:31116:32)
    at Scope.$apply (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:31405:25)
    at done (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:26563:48)
    at completeRequest (chrome-extension://lbofnchpcdkpnhhjilapocbhmjckcajm/scripts/main.build.js:26753:8)main.build.js:28511 (anonymous function)main.build.js:25461 (anonymous function)main.build.js:30095 processQueuemain.build.js:30103 (anonymous function)main.build.js:31300 Scope.$evalmain.build.js:31116 Scope.$digestmain.build.js:31405 Scope.$applymain.build.js:26563 donemain.build.js:26753 completeRequestmain.build.js:26694 requestLoaded
```

**Comment by kenji0919** [comment]
KONMAIが、bodyが不完全なページを返してくることが結構あるんじゃないかと睨んでいます。

**Comment by kenji0919** [comment]
![screen shot 2015-01-27 at 23 45 25](https://cloud.githubusercontent.com/assets/2742315/5920276/d63f8ca2-a67e-11e4-9a34-b83be7e4ee22.png)

多分こういう状態でしょうね…キレそうです。
一応statusページについては、 #91 で判定できるようにはしました。

**Comment by kenji0919** [comment]
この問題ですが、
- サーバ負荷が高い時に、それぞれのpageにアクセスする
- 空白のページが返ってきたら、#{page}_no_content.htmlとしてfixtureに追加する（各ファイルの@pageにも追加）
- 追加したfixtureを判定するテストをpage.coffeeに書く
- dl_result等の関数に、no_contentであれば、rejectするように追記する(まだ、使用していないページもあります)
という方法で解決したいと思います。

例のごとく、指定したページについて作業が完了したら、チェックボックスをつけましょう。

* [x] status
  * [x] fixture
  * [x] test
* [ ] music_list
  * [ ] fixture
  * [ ] test
* [ ] music_info
  * [ ] fixture
  * [ ] test
* [ ] rival
  * [ ] fixture
  * [ ] test
* [ ] rival_search
  * [ ] fixture
  * [ ] test
* [ ] rival_challenge
  * [ ] fixture
  * [ ] test
* [ ] reverse_rival
  * [ ] fixture
  * [ ] test
* [ ] follow
  * [ ] fixture
  * [ ] test
* [ ] follower
  * [ ] fixture
  * [ ] test
* [ ] recent
  * [ ] fixture
  * [ ] test
* [ ] mybest
  * [ ] fixture
  * [ ] test

**Comment by kenji0919** [comment]
また、dl_resultなどで、no_contentなページが返ってきて、reject後の処理をどうするかも、要検討です。

- 何もしない
- 指定時間後、再実行する
  - 最大リトライ回数を設定する必要がある
  - デメリット：$timeoutの導入が必要。（$timeoutはどちらにせよ、リクエストの間隔設定のために、近々入れますが）
- PirodxService.failed_list等のサービス変数（もしくは、コントローラ変数）を作って、そこに格納しておき、後で処理する（DBへの保存は不要だと思う）
  - failed_listに保存したリザルトは、画面に表示して失敗を通知する
  - もちろん、failed_listの名前とバージョンを使用して、リザルトを再取得しても良い
    - デメリット：timeoutで再実行するよりも、HTTPリクエストは増える（music_listの分）

**Comment by kenji0919** [comment]
ページのDLだけは済ませました。変換してaddしてPR投げます。

対策についてコメント頂けると嬉しいです。

**Comment by kenji0919** [comment]
#99

**Comment by kenji0919** [comment]
no_contentなページを判定できるようにしたので、
dl_*の関数を実行した時は、必ずget_page_typeをして、rejectするようにしましょう！

**Comment by suitougreentea** [comment]
ありがとうございました！
